import { Question } from './types'

export const batch1: Question[] = [
  {
    prompt: 'Manakah kalimat yang paling efektif?',
    choices: [
      'Kami semua bersama-sama ikut serta menanam pohon.',
      'Kami menanam pohon.',
      'Kami semua bersama-sama menanam pohon bersama.',
    ],
    answerIndex: 1,
    explanation: "Kalimat efektif ringkas, hindari pengulangan makna seperti 'semua' dan 'bersama-sama'.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat efektif untuk menyatakan waktu.',
    choices: ['Sekarang ini saat ini kami belajar.', 'Sekarang kami belajar.', 'Kami sekarang ini belajar.'],
    answerIndex: 1,
    explanation: "Gunakan satu keterangan waktu saja, tidak perlu 'sekarang ini' atau 'saat ini' ganda.",
    tag: 'efektif',
  },
  {
    prompt: 'Pilih kalimat efektif.',
    choices: ['Andi memanjat naik pohon.', 'Andi memanjat pohon.', 'Andi naik ke atas pohon.'],
    answerIndex: 1,
    explanation: "Hindari pleonasme seperti 'memanjat naik' atau 'naik ke atas'.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat efektif untuk perintah.',
    choices: ['Harap dimohon agar tenang!', 'Mohon tenang.', 'Harap dimohon untuk tenang.'],
    answerIndex: 1,
    explanation: "Kalimat efektif langsung ke tujuan: 'Mohon tenang.'",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat efektif untuk undangan.',
    choices: [
      'Diharapkan untuk dapat menghadiri acara sekolah.',
      'Silakan hadir dalam acara sekolah.',
      'Dimohonkan sekiranya untuk dapat menghadiri acara sekolah yang akan diadakan nanti.',
    ],
    answerIndex: 1,
    explanation: "Kalimat efektif singkat dan langsung: 'Silakan hadir dalam acara sekolah.'",
    tag: 'efektif',
  },
  {
    prompt: 'Pilih kalimat efektif.',
    choices: ['Para siswa-siswa membersihkan taman.', 'Para siswa membersihkan taman.', 'Siswa-siswa para membersihkan taman.'],
    answerIndex: 1,
    explanation: "Hindari bentuk jamak ganda 'para siswa-siswa'.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat efektif menyebut tempat.',
    choices: ['Kami bermain di halaman sekolah.', 'Kami bermain pada di halaman sekolah.', 'Kami bermain di pada halaman sekolah.'],
    answerIndex: 0,
    explanation: "Gunakan satu preposisi saja, yaitu 'di'.",
    tag: 'efektif',
  },
  {
    prompt: 'Pilih kalimat paling efektif.',
    choices: ['Bel berbunyi pada pukul jam 07.00 pagi.', 'Bel berbunyi pukul 07.00.', 'Bel berbunyi jam pukul 07.00 pagi hari.'],
    answerIndex: 1,
    explanation: "Hindari pengulangan kata 'pukul/jam' dan 'pagi hari'.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat efektif untuk larangan.',
    choices: ['Jangan berlari di koridor.', 'Dilarang untuk jangan berlari di koridor.', 'Harap supaya jangan berlari di koridor.'],
    answerIndex: 0,
    explanation: "Cukup 'Jangan + kata kerja'.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat efektif untuk penutup.',
    choices: [
      'Demikianlah maka oleh sebab itu terima kasih atas perhatiannya.',
      'Terima kasih atas perhatian.',
      'Dengan demikian maka terima kasih atas perhatiannya yang mana telah diberikan.',
    ],
    answerIndex: 1,
    explanation: "Gunakan bentuk baku dan ringkas.",
    tag: 'efektif',
  },
]

export const batch2: Question[] = [
  {
    prompt: 'Urutan SPOK yang benar adalah...',
    choices: [
      'Subjek–Predikat–Objek–Keterangan',
      'Predikat–Subjek–Objek–Keterangan',
      'Subjek–Objek–Predikat–Keterangan',
    ],
    answerIndex: 0,
    explanation: "Pola dasar kalimat bahasa Indonesia adalah S–P–O–K.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat berpola SPOK.',
    choices: ['Ani menulis surat di kamar.', 'Menulis surat Ani di kamar.', 'Surat menulis Ani di kamar.'],
    answerIndex: 0,
    explanation: "a memiliki S(Ani)–P(menulis)–O(surat)–K(di kamar).",
    tag: 'spok',
  },
  {
    prompt: 'Subjek pada kalimat "Ibu memasak nasi di dapur" adalah...',
    choices: ['Ibu', 'memasak', 'nasi'],
    answerIndex: 0,
    explanation: "Subjek = pelaku: 'Ibu'.",
    tag: 'spok',
  },
  {
    prompt: 'Predikat pada kalimat "Rudi membaca buku di rumah" adalah...',
    choices: ['Rudi', 'membaca', 'buku'],
    answerIndex: 1,
    explanation: "Predikat = kata kerja: 'membaca'.",
    tag: 'spok',
  },
  {
    prompt: 'Objek pada kalimat "Rani membeli pensil di toko" adalah...',
    choices: ['Rani', 'membeli', 'pensil'],
    answerIndex: 2,
    explanation: "Objek = 'pensil'.",
    tag: 'spok',
  },
  {
    prompt: 'Keterangan pada kalimat "Ayah mencuci mobil di garasi" adalah...',
    choices: ['Ayah', 'mobil', 'di garasi'],
    answerIndex: 2,
    explanation: "Keterangan tempat = 'di garasi'.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat mana yang bukan SPOK lengkap?',
    choices: ['Rina menyiram bunga di taman.', 'Rina menyiram di taman.', 'Rina menyiram bunga di taman.'],
    answerIndex: 1,
    explanation: "b tidak punya objek yang jelas.",
    tag: 'spok',
  },
  {
    prompt: 'Susunlah sesuai pola SPOK: "bola / Andi / menendang / di lapangan"',
    choices: [
      'Andi menendang bola di lapangan.',
      'Andi di lapangan menendang bola.',
      'Bola di lapangan Andi menendang.',
    ],
    answerIndex: 0,
    explanation: "Urutan SPOK: Andi (S) menendang (P) bola (O) di lapangan (K).",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat berpola SPOK yang benar.',
    choices: [
      'Budi membaca buku di perpustakaan.',
      'Budi di perpustakaan membaca buku.',
      'Di perpustakaan buku membaca Budi.',
    ],
    answerIndex: 0,
    explanation: "a paling alami mengikuti urutan SPOK.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat SPOK sederhana.',
    choices: ['Adik makan nasi di dapur.', 'Di dapur adik makan nasi.', 'Nasi makan adik di dapur.'],
    answerIndex: 0,
    explanation: "Urutan SPOK sesuai struktur dasar kalimat.",
    tag: 'spok',
  },
]

export const batch3: Question[] = [
  {
    prompt: 'Kalimat efektif yang benar.',
    choices: ['Ia batuk karena sebab flu.', 'Ia batuk karena flu.', 'Karena sebab flu maka ia batuk.'],
    answerIndex: 1,
    explanation: "Hindari kata berulang 'karena sebab'.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat berpola SPOK.',
    choices: ['Eka menggambar pemandangan di buku.', 'Pemandangan menggambar Eka di buku.', 'Di buku Eka menggambar pemandangan.'],
    answerIndex: 0,
    explanation: "S–P–O–K: Eka (S) menggambar (P) pemandangan (O) di buku (K).",
    tag: 'spok',
  },
  {
    prompt: 'Subjek pada kalimat "Sinta menanam bunga di taman" adalah...',
    choices: ['Sinta', 'menanam', 'bunga'],
    answerIndex: 0,
    explanation: "Subjek = pelaku: 'Sinta'.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif untuk ajakan.',
    choices: ['Mari kita belajar bersama.', 'Ayo mari kita bersama-sama belajar.', 'Mari ayo kita bersama-sama untuk belajar.'],
    answerIndex: 0,
    explanation: "Cukup satu kata ajakan, 'Mari'.",
    tag: 'efektif',
  },
  {
    prompt: 'Objek pada kalimat "Tono menendang bola di lapangan" adalah...',
    choices: ['Tono', 'menendang', 'bola'],
    answerIndex: 2,
    explanation: "Objek = 'bola'.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif untuk larangan.',
    choices: ['Jangan makan sambil berbicara.', 'Harap jangan untuk makan sambil berbicara.', 'Jangan untuk makan sambil berbicara.'],
    answerIndex: 0,
    explanation: "Gunakan bentuk larangan langsung: 'Jangan + kata kerja'.",
    tag: 'efektif',
  },
  {
    prompt: 'Predikat pada kalimat "Dewi menyapu lantai di ruang kelas" adalah...',
    choices: ['Dewi', 'menyapu', 'lantai'],
    answerIndex: 1,
    explanation: "Predikat = kata kerja.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif untuk menyatakan tujuan.',
    choices: ['Saya belajar supaya mendapat nilai baik.', 'Saya belajar supaya agar mendapat nilai baik.', 'Supaya agar saya belajar.'],
    answerIndex: 0,
    explanation: "Gunakan satu kata penghubung, tidak 'supaya agar'.",
    tag: 'efektif',
  },
  {
    prompt: 'Keterangan pada kalimat "Beni bermain bola di halaman" adalah...',
    choices: ['Beni', 'bola', 'di halaman'],
    answerIndex: 2,
    explanation: "Keterangan tempat = 'di halaman'.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat SPOK yang benar.',
    choices: ['Mereka makan siang di kantin.', 'Makan siang mereka di kantin.', 'Di kantin mereka makan siang.'],
    answerIndex: 0,
    explanation: "Urutan SPOK paling tepat pada pilihan a.",
    tag: 'spok',
  },
]

export const batch4: Question[] = [
  {
    prompt: 'Kalimat efektif untuk menyatakan hasil.',
    choices: ['Ia berhasil karena usahanya.', 'Ia berhasil sebab karena usahanya.', 'Karena sebab usahanya ia berhasil.'],
    answerIndex: 0,
    explanation: "Hindari 'sebab karena' ganda.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat SPOK yang benar.',
    choices: ['Paman memperbaiki sepeda di garasi.', 'Sepeda paman memperbaiki di garasi.', 'Di garasi memperbaiki paman sepeda.'],
    answerIndex: 0,
    explanation: "a lengkap: S–P–O–K.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif menyebut waktu.',
    choices: ['Kami belajar setiap pagi.', 'Setiap pagi hari kami belajar setiap pagi.', 'Kami belajar setiap pagi hari di pagi hari.'],
    answerIndex: 0,
    explanation: "Gunakan satu keterangan waktu saja.",
    tag: 'efektif',
  },
  {
    prompt: 'SPOK: "kue / memotong / Rani / di dapur"',
    choices: [
      'Rani memotong kue di dapur.',
      'Rani di dapur memotong kue.',
      'Kue Rani memotong di dapur.',
    ],
    answerIndex: 0,
    explanation: "a paling tepat mengikuti S–P–O–K.",
    tag: 'spok',
  },
  {
    prompt: 'Predikat pada kalimat "Ayah menulis surat di ruang tamu" adalah...',
    choices: ['Ayah', 'menulis', 'surat'],
    answerIndex: 1,
    explanation: "Predikat = kata kerja 'menulis'.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif untuk perintah.',
    choices: ['Tolong buka jendela.', 'Dimohon untuk agar jendela dibuka.', 'Harap supaya tolong buka jendela.'],
    answerIndex: 0,
    explanation: "Kalimat efektif langsung dan singkat.",
    tag: 'efektif',
  },
  {
    prompt: 'Kalimat SPOK yang benar.',
    choices: [
      'Lani membawa tas ke sekolah.',
      'Tas membawa Lani ke sekolah.',
      'Ke sekolah membawa tas Lani.',
    ],
    answerIndex: 0,
    explanation: "a lengkap: S(Lani)–P(membawa)–O(tas)–K(ke sekolah).",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif untuk undangan.',
    choices: [
      'Silakan hadir pada acara sekolah.',
      'Diharapkan untuk dapat hadir pada acara sekolah.',
      'Dimohonkan sekiranya agar dapat menghadiri acara sekolah.',
    ],
    answerIndex: 0,
    explanation: "Langsung dan mudah dipahami.",
    tag: 'efektif',
  },
  {
    prompt: 'Keterangan pada kalimat "Riko mencuci piring di dapur" adalah...',
    choices: ['Riko', 'piring', 'di dapur'],
    answerIndex: 2,
    explanation: "Keterangan tempat = 'di dapur'.",
    tag: 'spok',
  },
  {
    prompt: 'Kalimat efektif untuk penutup surat.',
    choices: ['Terima kasih atas perhatian.', 'Demikianlah maka terima kasih atas perhatiannya yang mana.', 'Dengan demikian oleh sebab itu terima kasih.'],
    answerIndex: 0,
    explanation: "Gunakan bentuk baku dan ringkas.",
    tag: 'efektif',
  },
]

export const batches = [batch1, batch2, batch3, batch4]
